version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13
    container_name: postgres-geo-locator
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo-locator-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
