version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13
    container_name: postgres-geo-locator
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo-locator-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # quarkus:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: src\main\docker\Dockerfile.jvm
  #   container_name: quarkus-app
  #   environment:
  #     QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/geo-locator-db
  #     QUARKUS_DATASOURCE_USERNAME: postgres
  #     QUARKUS_DATASOURCE_PASSWORD: postgres
  #   ports:
  #     - "8085:8085"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
